feature: support vue 2.x
DamianOsipiuk/vue-react-query pull request #2
Opened 2021-04-04 08:47 UTC by jueinin

close #1

2021-04-04 08:54 UTC, jueinin commented
there are two failed test case . and i do not know the reason....

sorry. i will work on it continuously.

hope for your help.

2021-04-05 00:55 UTC, jueinin commented
do you have the time to review code? 

1. set typescript target to es6. the optional chain syntax needs to be transpiled
2. add vue-demi to support vue 2.x
3. add entry point on rollup config. now we should import devtool by `import {} from 'vue-react-query/lib/devtool'`


there are two failed test case . and i do not know the reason....

2021-04-06 07:59 UTC, DamianOsipiuk requested changes
Hi, could you also add a minimal project in the `examples` directory that will be using Vue 2?
I guess it will add value for people that will try to use it. Also as a way of checking if lib is working with Vue 2 after changes.

2021-04-06 07:59 UTC, DamianOsipiuk commented on package.json
> +    "vue": "^2.0.0 || >=3.0.0-rc.0"
Since Vue 3 is already released and considered stable, I would prefer to add at least Vue 3.0.0 as a dependency.

2021-04-06 07:59 UTC, DamianOsipiuk commented on rollup.config.ts
> +      name: "VueQuery",
I feel that this should be named as `VueQueryDevtools`

2021-04-06 07:59 UTC, DamianOsipiuk commented on src/devtools/CloseButton.vue
> +import { computed, defineComponent, PropType } from "vue-demi";
Since dev-tools will not be compatible with Vue 2 anyway for now, you can leave the imports as-is

2021-04-06 07:59 UTC, DamianOsipiuk commented on tests/useInfiniteQuery.test.ts
> +  const vue = jest.requireActual("vue-demi");
I believe that you can leave imports in tests as-is, this should solve your issue with failing tests.

2021-04-07 15:45 UTC, jueinin commented
i will. could you wait me until weekend？ It's too busy recently😂😂

2021-04-10 04:34 UTC, jueinin commented
I got it!. now all hooks should support vue2.x. but i still have no idea on those two failed test case...

2021-04-11 13:15 UTC, DamianOsipiuk approved these changes

2021-04-11 13:17 UTC, DamianOsipiuk commented
I will fix the tests later today and release a new version.
Thanks for taking care of this @jueinin

2021-04-11 13:17 UTC, merged